// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJpVwNH1FECdOF-U27Lew7-IiBRouI28c',
    appId: '1:203475343681:web:e6e53a02b1efcd384329c0',
    messagingSenderId: '203475343681',
    projectId: 'ferrous-record-421116',
    authDomain: 'ferrous-record-421116.firebaseapp.com',
    storageBucket: 'ferrous-record-421116.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATw5kqqfB4bwTQrR32qICeBM5Gybhe6y4',
    appId: '1:203475343681:android:ca24f76122e8e9ed4329c0',
    messagingSenderId: '203475343681',
    projectId: 'ferrous-record-421116',
    storageBucket: 'ferrous-record-421116.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJpvSzI6tdZzurksiFSjN1isNp_SSJnW8',
    appId: '1:203475343681:ios:81d0a39156ca13f44329c0',
    messagingSenderId: '203475343681',
    projectId: 'ferrous-record-421116',
    storageBucket: 'ferrous-record-421116.firebasestorage.app',
    iosBundleId: 'com.example.minibuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJpvSzI6tdZzurksiFSjN1isNp_SSJnW8',
    appId: '1:203475343681:ios:81d0a39156ca13f44329c0',
    messagingSenderId: '203475343681',
    projectId: 'ferrous-record-421116',
    storageBucket: 'ferrous-record-421116.firebasestorage.app',
    iosBundleId: 'com.example.minibuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJpVwNH1FECdOF-U27Lew7-IiBRouI28c',
    appId: '1:203475343681:web:7259d292d46299704329c0',
    messagingSenderId: '203475343681',
    projectId: 'ferrous-record-421116',
    authDomain: 'ferrous-record-421116.firebaseapp.com',
    storageBucket: 'ferrous-record-421116.firebasestorage.app',
  );
}
